/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaGL */

#ifndef _Included_JavaGL
#define _Included_JavaGL
#ifdef __cplusplus
extern "C" {
#endif
#undef JavaGL_FOCUS_TRAVERSABLE_UNKNOWN
#define JavaGL_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef JavaGL_FOCUS_TRAVERSABLE_DEFAULT
#define JavaGL_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef JavaGL_FOCUS_TRAVERSABLE_SET
#define JavaGL_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef JavaGL_TOP_ALIGNMENT
#define JavaGL_TOP_ALIGNMENT 0.0f
#undef JavaGL_CENTER_ALIGNMENT
#define JavaGL_CENTER_ALIGNMENT 0.5f
#undef JavaGL_BOTTOM_ALIGNMENT
#define JavaGL_BOTTOM_ALIGNMENT 1.0f
#undef JavaGL_LEFT_ALIGNMENT
#define JavaGL_LEFT_ALIGNMENT 0.0f
#undef JavaGL_RIGHT_ALIGNMENT
#define JavaGL_RIGHT_ALIGNMENT 1.0f
#undef JavaGL_serialVersionUID
#define JavaGL_serialVersionUID -7644114512714619750i64
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
/* Inaccessible static: nameCounter */
#undef JavaGL_serialVersionUID
#define JavaGL_serialVersionUID -2284879212465893870i64
/* Inaccessible static: class_00024gl4java_00024awt_00024GLAnimCanvas */
/* Inaccessible static: globalThreadNumber */
/*
 * Class:     JavaGL
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JavaGL_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     JavaGL
 * Method:    reshapeCanvas
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaGL_reshapeCanvas
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaGL
 * Method:    renderScene
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaGL_renderScene
  (JNIEnv *, jobject);

/*
 * Class:     JavaGL
 * Method:    scriptIsDone
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JavaGL_scriptIsDone
  (JNIEnv *, jobject);

/*
 * Class:     JavaGL
 * Method:    pickPoint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaGL_pickPoint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaGL
 * Method:    lockPoint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaGL_lockPoint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaGL
 * Method:    dragPoint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaGL_dragPoint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaGL
 * Method:    mouseRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaGL_mouseRelease
  (JNIEnv *, jobject);

/*
 * Class:     JavaGL
 * Method:    getLockedArray
 * Signature: ()[F
 */
JNIEXPORT jintArray JNICALL Java_JavaGL_getLockedArray
  (JNIEnv*, jobject);

/*
 * Class:     JavaGL
 * Method:    loadFilename
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_JavaGL_loadFilename
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     JavaGL
 * Method:    performAction
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaGL_performAction
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
